import {
  INGREDIENT_TYPE,
  IngredientType,
  OrderResponseType,
  OrderType,
} from '../services/types/types';

export const data: IngredientType[] = [
  {
    _id: '60666c42cc7b410027a1a9b1',
    name: 'Краторная булка N-200i',
    type: INGREDIENT_TYPE.Bun,
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b5',
    name: 'Говяжий метеорит (отбивная)',
    type: INGREDIENT_TYPE.Main,
    proteins: 800,
    fat: 800,
    carbohydrates: 300,
    calories: 2674,
    price: 3000,
    image: 'https://code.s3.yandex.net/react/code/meat-04.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-04-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-04-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b6',
    name: 'Биокотлета из марсианской Магнолии',
    type: INGREDIENT_TYPE.Main,
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 424,
    image: 'https://code.s3.yandex.net/react/code/meat-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-01-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b7',
    name: 'Соус Spicy-X',
    type: INGREDIENT_TYPE.Sauce,
    proteins: 30,
    fat: 20,
    carbohydrates: 40,
    calories: 30,
    price: 90,
    image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b4',
    name: 'Мясо бессмертных моллюсков Protostomia',
    type: INGREDIENT_TYPE.Main,
    proteins: 433,
    fat: 244,
    carbohydrates: 33,
    calories: 420,
    price: 1337,
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b9',
    name: 'Соус традиционный галактический',
    type: INGREDIENT_TYPE.Sauce,
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
    calories: 99,
    price: 15,
    image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b8',
    name: 'Соус фирменный Space Sauce',
    type: INGREDIENT_TYPE.Sauce,
    proteins: 50,
    fat: 22,
    carbohydrates: 11,
    calories: 14,
    price: 80,
    image: 'https://code.s3.yandex.net/react/code/sauce-04.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-04-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-04-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bc',
    name: 'Плоды Фалленианского дерева',
    type: INGREDIENT_TYPE.Main,
    proteins: 20,
    fat: 5,
    carbohydrates: 55,
    calories: 77,
    price: 874,
    image: 'https://code.s3.yandex.net/react/code/sp_1.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bb',
    name: 'Хрустящие минеральные кольца',
    type: INGREDIENT_TYPE.Main,
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
    calories: 986,
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9ba',
    name: 'Соус с шипами Антарианского плоскоходца',
    type: INGREDIENT_TYPE.Sauce,
    proteins: 101,
    fat: 99,
    carbohydrates: 100,
    calories: 100,
    price: 88,
    image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bd',
    name: 'Кристаллы марсианских альфа-сахаридов',
    type: INGREDIENT_TYPE.Main,
    proteins: 234,
    fat: 432,
    carbohydrates: 111,
    calories: 189,
    price: 762,
    image: 'https://code.s3.yandex.net/react/code/core.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9be',
    name: 'Мини-салат Экзо-Плантаго',
    type: INGREDIENT_TYPE.Main,
    proteins: 1,
    fat: 2,
    carbohydrates: 3,
    calories: 6,
    price: 4400,
    image: 'https://code.s3.yandex.net/react/code/salad.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b3',
    name: 'Филе Люминесцентного тетраодонтимформа',
    type: INGREDIENT_TYPE.Main,
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: 'https://code.s3.yandex.net/react/code/meat-03.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bf',
    name: 'Сыр с астероидной плесенью',
    type: INGREDIENT_TYPE.Main,
    proteins: 84,
    fat: 48,
    carbohydrates: 420,
    calories: 3377,
    price: 4142,
    image: 'https://code.s3.yandex.net/react/code/cheese.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b2',
    name: 'Флюоресцентная булка R2-D3',
    type: INGREDIENT_TYPE.Bun,
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: 'https://code.s3.yandex.net/react/code/bun-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
  },
];

export const mockOrderData: OrderType = {
  _id: '68f3a612b9d496001c83a5db',
  status: 'done',
  name: 'Space флюоресцентный бургер',
  createdAt: '2024-03-13T10:30:00.000Z',
  updatedAt: '2025-10-18T14:37:07.517Z',
  number: 91658,
  ingredients: [data[1], data[3], data[5]],
};

export const mockCreateOrderResponse = {
  success: true,
  name: 'Space Spicy Burger',
  order: mockOrderData,
};

export const emptyOrderResponse: OrderResponseType = {
  orders: [],
  success: true,
  total: 0,
  totalToday: 0,
};

export const mockOrderResponse: OrderResponseType = {
  orders: [
    {
      _id: '68f3a612b9d496001c83a5db',
      status: 'done',
      name: 'Space флюоресцентный бургер',
      createdAt: '2024-03-13T10:30:00.000Z',
      updatedAt: '2025-10-18T14:37:07.517Z',
      number: 91658,
      ingredients: [data[2], data[5]],
    },
    {
      _id: '658f3a612eb9d49683a5db',
      status: 'done',
      name: 'Краторная булка N-200i',
      createdAt: '2024-03-13T10:30:00.000Z',
      updatedAt: '2025-10-18T14:37:07.517Z',
      number: 91658,
      ingredients: [data[0]],
    },
  ],
  success: true,
  total: 100,
  totalToday: 10,
};

export const mockSendOrder = {
  name: 'Краторный антарианский бургер',
  order: {
    createdAt: '2025-10-18T15:42:59.415Z',
    ingredients: [],
    name: 'Краторный антарианский бургер',
    number: 91659,
    owner: {
      createdAt: '2025-09-04T14:39:00.926Z',
      email: 'elisza087@gmail.com',
      name: 'inna',
      updatedAt: '2025-10-06T16:35:43.646Z',
    },
    price: 1343,
    status: 'done',
    updatedAt: '2025-10-18T15:43:00.436Z',
    _id: '68f3b583b9d496001c83a5e5',
  },
};

export const mockNewUser = {
  email: 'test@gmail.com',
  password: '12345',
  name: 'Inna',
};
